"""Test 8 - steerability: can the prefix be pushed to raise log p("{") at the last prompt position?

Objective: mean over the 32 held-out prompts of log p(next token = "{") at the LAST prompt position
(receiver_forward output, index -1), with the prefix before the prompt as in training.

(a) direct: the 16 prefix vectors are free parameters, one (16, H) set PER PROMPT ([32, 16, H]),
    initialised from each start (step0 / step1000 / best gists, text16, zeros); everything else frozen.
    Adam, 50 steps, LR 1e-3 and 1e-2.
(b) through the generator: from the step0 and best checkpoints, the generator's training trainable set
    (Embedding2 + LM_head + last 3 layers, _common.trainable_params) is optimised with AdamW, LR 1e-4,
    clip_grad_norm_ 1.0, 50 steps, gists regenerated by generate_softprompt every step.
Reported: mean target log-prob at steps 0/10/25/50 (step k = after k updates), total gain, and the
training KD loss on the 32 held-out prompts before and at step 50.
Each step uses all 32 prompts (8 batches of 4, gradients accumulated, loss / 8).
"""

import argparse
import statistics

import torch

from _gist_common import (
    L, NUM_LAYERS, Setup, batch_split, generate_softprompt, receiver_forward, save_json,
)
from _common import trainable_params

TARGET = "{"
STEPS = 50
RECORD = (0, 10, 25, 50)
DIRECT_LRS = (1e-3, 1e-2)
GEN_LR = 1e-4


def target_logprob(s, prefix, ids, tid):
    logits = receiver_forward(s.receiver, prefix, ids)[:, -1, :]
    return torch.log_softmax(logits, -1)[:, tid]            # (B,)


@torch.no_grad()
def heldout_kd(s, prefix, ids, teacher):
    vals = sum((s.per_prompt_kd(pb, ib, tb) for pb, ib, tb in
                zip(batch_split(prefix), batch_split(ids), batch_split(teacher))), [])
    return statistics.mean(vals)


def run_direct(s, init, ids, teacher, tid, lr):
    prefix = torch.nn.Parameter(init.detach().clone())
    opt = torch.optim.Adam([prefix], lr=lr)
    kd0 = heldout_kd(s, prefix.detach(), ids, teacher)
    trace = {}
    for step in range(STEPS + 1):
        opt.zero_grad()
        vals = []
        for pb, ib in zip(batch_split(prefix), batch_split(ids)):
            lp = target_logprob(s, pb, ib, tid)
            (-lp.mean() / (ids.shape[0] // ib.shape[0])).backward()
            vals += lp.detach().tolist()
        if step in RECORD:
            trace[step] = statistics.mean(vals)
        if step < STEPS:
            opt.step()
    kd50 = heldout_kd(s, prefix.detach(), ids, teacher)
    return {"target_logprob": trace, "gain": trace[STEPS] - trace[0], "heldout_kd_step0": kd0,
            "heldout_kd_step50": kd50}


def run_generator(s, ids, teacher, tid):
    params = trainable_params(s.encoder, s.embedding2, NUM_LAYERS)
    opt = torch.optim.AdamW(params, lr=GEN_LR)
    kd0 = heldout_kd(s, s.gists(s.heldout), ids, teacher)
    trace, gnorms = {}, []
    for step in range(STEPS + 1):
        opt.zero_grad(set_to_none=True)
        vals = []
        for ib in batch_split(ids):
            gist = generate_softprompt(s.encoder, s.embedding2, ib, L)
            lp = target_logprob(s, gist, ib, tid)
            (-lp.mean() / (ids.shape[0] // ib.shape[0])).backward()
            vals += lp.detach().tolist()
        if step in RECORD:
            trace[step] = statistics.mean(vals)
            print(f"   step {step}: target logprob {trace[step]:.4f}")
        if step < STEPS:
            gnorms.append(torch.nn.utils.clip_grad_norm_(params, max_norm=1.0).item())
            opt.step()
    kd50 = heldout_kd(s, s.gists(s.heldout), ids, teacher)
    return {"target_logprob": trace, "gain": trace[STEPS] - trace[0], "heldout_kd_step0": kd0,
            "heldout_kd_step50": kd50, "preclip_grad_norm_mean": statistics.mean(gnorms),
            "preclip_grad_norm_max": max(gnorms)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--part", choices=["a", "b", "both"], default="both")
    args = ap.parse_args()
    s = Setup()
    torch.manual_seed(0)
    tid = s.tok(TARGET, add_special_tokens=False)["input_ids"]
    assert len(tid) == 1, tid
    tid = tid[0]
    ids = torch.cat(s.heldout).to(s.device)
    teacher = torch.cat([s.teacher_logits(b) for b in batch_split(ids)])
    out = {"info": s.info(), "target": {"token": TARGET, "id": tid}, "steps": STEPS,
           "direct_lrs": list(DIRECT_LRS), "generator_lr": GEN_LR, "results": {"direct": {}, "generator": {}}}

    if args.part in ("a", "both"):
        starts = {}
        for name in s.names:
            s.use(name)
            starts[f"gist_{name}"] = s.gists(s.heldout)
        refs = s.reference_prefixes()
        for r in ("text16", "zeros"):
            starts[r] = refs[r].unsqueeze(0).expand(ids.shape[0], -1, -1)
        for sname, init in starts.items():
            for lr in DIRECT_LRS:
                r = run_direct(s, init, ids, teacher, tid, lr)
                out["results"]["direct"][f"{sname}@lr{lr:g}"] = r
                print(f"(a) {sname:14s} lr={lr:g}: " + " ".join(f"s{k}={v:.3f}" for k, v in
                      r["target_logprob"].items()) + f"  gain={r['gain']:+.3f}  "
                      f"KD {r['heldout_kd_step0']:.4f}->{r['heldout_kd_step50']:.4f}")
        save_json("t8_steer.json", out)

    if args.part in ("b", "both"):
        for name in ("step0", "best"):
            if name not in s.names:
                print(f"(b) {name} missing -- skipped")
                continue
            s.use(name)
            print(f"(b) generator from {name}")
            r = run_generator(s, ids, teacher, tid)
            out["results"]["generator"][name] = r
            print(f"(b) {name}: gain={r['gain']:+.3f}  KD {r['heldout_kd_step0']:.4f}->{r['heldout_kd_step50']:.4f}")
        if args.part == "b":
            import json, os
            from _gist_common import RESULTS_DIR
            p = os.path.join(RESULTS_DIR, "t8_steer.json")
            if os.path.exists(p):
                prev = json.load(open(p))
                prev["results"]["generator"] = out["results"]["generator"]
                out = prev
        save_json("t8_steer.json", out)


if __name__ == "__main__":
    main()
